version: '3.9'

networks:
  dev_org_net:

services:

  web:
    container_name: nginx-1.22_php-8.0.29r0
    image: dec24th82/complex:nginx-php8-node
    volumes:
      - ./src:/var/www/dev.org/html/public
      - ./config/certs:/etc/nginx/certs
      - ./config/web/nginx/fpm-pool.conf:/etc/php8/php-fpm.d/www.conf
      - ./config/web/php/php.ini:/etc/php8/conf.d/custom.ini
      - ./config/web/nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "${APP_PORT}:80"
      - "${APP_TLS_PORT}:443"
    networks:
      - dev_org_net
